spring.application.name=classOfferingBookingSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/classDB
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
